import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import source from '../assets/guillotinaReference';
import { notesApi } from '../api/notesApi';
import SocialLinks from '../components/SocialLinks';

const Fragment=({note,children})=>{const unit=n=>`${(n/1055*100).toFixed(5)}cqw`;return <section className={`fragment fragment--${note.fragment}`} style={{'--left':unit(note.x),'--top':unit(note.y-440),'--width':unit(note.w),'--height':unit(note.h),'--image-left':unit(-note.x),'--image-top':unit(-note.y)}} aria-label={note.title}><img src={source} alt="" />{children}</section>};

const Note=({note,open,onToggle,comments,onAddComment,onUpvote})=>{const [draft,setDraft]=useState('');const [copied,setCopied]=useState(false);useEffect(()=>{if(!open)return;const escape=e=>e.key==='Escape'&&onToggle();window.addEventListener('keydown',escape);return()=>window.removeEventListener('keydown',escape)},[open,onToggle]);const addComment=async e=>{e.preventDefault();const body=draft.trim();if(!body)return;await onAddComment(note.id,body);setDraft('')};const copyLink=async()=>{try{await navigator.clipboard?.writeText(window.location.href)}catch{}setCopied(true);setTimeout(()=>setCopied(false),1600)};return <article className={`story-note story-note--${note.tone} ${open?'is-open':''}`}><button type="button" onClick={onToggle} aria-expanded={open}><span>{open?'CERRAR −':'LEER +'} </span><strong>{note.title}</strong><small>{note.subtitle}</small></button>{open&&createPortal(<div className="note-modal" role="dialog" aria-modal="true" aria-label={note.title}><button className="note-modal__backdrop" onClick={onToggle} aria-label="Cerrar nota"/><section className={`note-modal__panel note-modal__panel--${note.tone}`}><header className="note-modal__header"><span>NOTA / {note.tone.toUpperCase()}</span><button type="button" onClick={onToggle}>CERRAR ×</button></header><div className="note-modal__content"><div className="note-modal__intro"><p>{note.subtitle}</p><h2>{note.title}</h2><div className="note-modal__actions"><button type="button" onClick={copyLink}>{copied?'ENLACE COPIADO':'COMPARTIR ↗'}</button><button type="button" onClick={()=>document.querySelector('.note-modal__comments')?.scrollIntoView({behavior:'smooth'})}>COMENTAR ↓</button></div></div><div className="note-modal__article">{note.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{note.editionLink&&<Link to="/edicion/n-001-la-grieta">Ver índice completo →</Link>}<p>Esta nota forma parte de una lectura abierta: podés volver a ella, compartirla y dejar una idea para que el texto siga circulando.</p></div><section className="note-modal__comments"><h3>Comentarios <span>{comments.length}</span></h3><div className="comment-list">{comments.map(comment=><article className="comment" key={comment.id}><b>{comment.author}</b><p>{comment.body}</p><button type="button" onClick={()=>onUpvote(note.id,comment.id)}>↑ útil {comment.votes}</button></article>)}</div><form onSubmit={addComment}><label htmlFor={`comment-${note.id}`}>Sumá tu voz</label><textarea id={`comment-${note.id}`} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Escribí tu comentario…" rows="4"/><button type="submit">PUBLICAR COMENTARIO →</button></form></section></div></section></div>,document.body)}</article>};

export default function Home(){const [home,setHome]=useState(null);const [comments,setComments]=useState({});const [activeNote,setActiveNote]=useState(null);const [error,setError]=useState('');useEffect(()=>{notesApi.getEditionHome().then(async data=>{setHome(data);const pairs=await Promise.all(data.notes.map(async note=>[note.id,await notesApi.getComments(note.id)]));setComments(Object.fromEntries(pairs))}).catch(()=>setError('No pudimos cargar la edición.'));},[]);const toggle=id=>setActiveNote(current=>current===id?null:id);const addComment=async(noteId,body)=>{const comment=await notesApi.createComment(noteId,{body});setComments(current=>({...current,[noteId]:[...(current[noteId]??[]),comment]}))};const upvote=async(noteId,commentId)=>{const updated=await notesApi.upvoteComment(noteId,commentId);setComments(current=>({...current,[noteId]:(current[noteId]??[]).map(comment=>comment.id===commentId?updated:comment)}))};useEffect(()=>{if(!activeNote||!home)return;const onKeyDown=event=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;const index=home.notes.findIndex(note=>note.id===activeNote);if(event.key==='Escape')setActiveNote(null);if(event.key==='ArrowRight'){event.preventDefault();setActiveNote(home.notes[(index+1)%home.notes.length].id)}if(event.key==='ArrowLeft'){event.preventDefault();setActiveNote(home.notes[(index-1+home.notes.length)%home.notes.length].id)}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown)},[activeNote,home]);if(error)return <p className="home-status" role="alert">{error}</p>;if(!home)return <p className="home-status" role="status">Cargando edición…</p>;return <article className="publication"><section className="fragment fragment--masthead" aria-label="Portada de La Guillotina"><img src={source} alt="Portada de La Guillotina" /></section><nav className="publication-nav" aria-label="Navegación de la revista">{home.edition.navigation.map(item=><Link key={item.to} to={item.to}>{item.label}</Link>)}</nav><div className="edition-canvas" aria-label={`Edición ${home.edition.number}`}>{home.notes.map(note=><Fragment key={note.id} note={note}><Note note={note} open={activeNote===note.id} onToggle={()=>toggle(note.id)} comments={comments[note.id]??[]} onAddComment={addComment} onUpvote={upvote}/></Fragment>)}<Link className="edition-hotspot" to={`/edicion/${home.edition.id}`} aria-label="Abrir edición" /></div><footer className="publication-imprint"><div><b>{home.edition.publication}</b><span>REVISTA ANARQUISTA · EDICIÓN {home.edition.number}</span></div><p>HECHA SIN AMO · SIN COPYRIGHT · COPIÁ · DIFUNDÍ · ORGANIZATE</p><SocialLinks/></footer></article>}
